language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
addons:
  firefox: 45.8.0esr
env:
- PLONE_VERSION=4.3 TEST_EGGS=collective.cover[test]
- PLONE_VERSION=5.0
- PLONE_VERSION=5.1
matrix:
  fast_finish: true
install:
- sed -ie "s#test-4.3#test-$PLONE_VERSION#" buildout.cfg
- sed -ie "s#versions-4.3#versions-$PLONE_VERSION#" buildout.cfg
- python bootstrap.py
- bin/buildout buildout:test-eggs=$TEST_EGGS annotate
- bin/buildout buildout:test-eggs=$TEST_EGGS
before_script:
- export DISPLAY=:99.0
- export GROK_DISABLE_TEMPLATE_WARNING=on
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
- bin/code-analysis
- CATALOG_OPTIMIZATION_DISABLED=true bin/test
after_success:
- bin/createcoverage --output-dir=htmlcov -t "--layer=!Robot"
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
